# Generated by Django 2.2 on 2021-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindak_pidana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tindak_Pidana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_TP', models.CharField(max_length=30)),
                ('pasal_TP', models.CharField(max_length=30)),
                ('kategori_TP', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
