# Generated by Django 2.2 on 2021-04-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindak_pidana', '0002_auto_20210401_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tindak_Pidana',
            new_name='Kategori',
        ),
    ]
